[General]
core=0
engine=0
akaudio=0
gfxui=0
gameframework=0
gearboxframework=0
ipdrv=0
onlinesubsystemsteamworks=0
onlinesubsystemepicstore=0
willowgame=0
menumap=0
startup=0
startup_loc_int=0

; Borderlands: The Pre-Sequel
startup_loc_deu=0
startup_loc_esn=0
startup_loc_fra=0
startup_loc_ita=0
startup_loc_jpn=0
startup_loc_kor=0
startup_loc_rus=0

[DLC]
; Borderlands 2
allium=0			; Headhunters 2/3 (Wattle Gobbler & Mercenary Day)
anecana=0			; Ultra HD Texture Pack (Fight for Sanctuary)
anemone=0			; Fight for Sanctuary
aster=0				; Assault on Dragon Keep
commday2013=0		; Community Day 2013 Customizations
flax=0				; Headhunter 1 (Bloody Harvest)
gardenia01=0		; Customizations Pack 1
gardenia04=0		; Customizations Pack 2
gardenia05=0		; Customizations Pack 3
gladiolus=0			; Ultimate Vault Hunter Upgrade Pack 1
iris=0				; Campaign of Carnage
lilac=0				; Psycho Pack (Krieg)
lobelia=0			; Ultimate Vault Hunter Upgrade Pack 2 (The Raid on Digistruct Peak)
lootchest2=0		; Ultimate Loot Chest Customizations
mancana=0			; Ultra HD Texture Pack
nasturtium=0		; Headhunters 4/5 (Wedding Day Massacre & Son of Crawmerax)
orchid=0			; Pirate's Booty
peony=0				; Pre-Sequel Customizations
pn2=0				; Pocker Night at the Inventory 2 Customizations
pocollectors=0		; Collector's Edition Pre-Order Bonus
pogamestop=0		; GameStop Pre-Order Bonus
popremierclub=0		; Premier Club Pre-Order Bonus
sage=0				; Big Game Hunt
tulip=0				; Mechromancer Pack (Gaige)

; Borderlands: The Pre-Sequel
ailanthus=0			; Ultra HD Texture Pack
crocus=0			; Baroness Pack (Aurelia)
;freesia=0			; Shock Drop Slaughter Pit
maingamerefs=0		; UNUSED - Can be used for custom content!
marigold=0			; Claptastic Voyage & Ultimate Vault Hunter Upgrade Pack 2
petunia=0			; Ultimate Vault Hunter Upgrade Pack 1 (The Holodome Onslaught)
quince=0			; Doppelganger Pack (Jack)

[Console]
EnableConsoleCommands=1		; Remove the "say" prefix and enable "exec" commands. Disable this option if you use the SDK!
RemoveArraySizeLimit=1		; Remove the hardcoded array size limit from object dumps in the console (BL2 & TPS only).
