[General]
core=0
engine=0
akaudio=0
gfxui=0
gameframework=0
gearboxframework=0
ipdrv=0
onlinesubsystemsteamworks=0
onlinesubsystemepicstore=0
willowgame=1
menumap=0
startup=1
startup_loc_int=0

; Borderlands: The Pre-Sequel
startup_loc_deu=0
startup_loc_esn=0
startup_loc_fra=0
startup_loc_ita=0
startup_loc_jpn=0
startup_loc_kor=0
startup_loc_rus=0

[DLC]
; Borderlands 2
allium=0			; Headhunters 2/3 (Wattle Gobbler & Mercenary Day)
anemone=0			; Fight for Sanctuary
aster=0				; Assault on Dragon Keep
flax=0				; Headhunter 1 (Bloody Harvest)
gladiolus=0			; Ultimate Vault Hunter Upgrade Pack 1
iris=0				; Campaign of Carnage
lilac=0				; Psycho Pack (Krieg)
lobelia=0			; Ultimate Vault Hunter Upgrade Pack 2 (The Raid on Digistruct Peak)
nasturtium=0			; Headhunters 4/5 (Wedding Day Massacre & Son of Crawmerax)
orchid=0			; Pirate's Booty
sage=0				; Big Game Hunt
tulip=0				; Mechromancer Pack (Gaige)

; Borderlands: The Pre-Sequel
crocus=0			; Baroness Pack (Aurelia)
marigold=0			; Claptastic Voyage & Ultimate Vault Hunter Upgrade Pack 2
petunia=0			; Ultimate Vault Hunter Upgrade Pack 1 (The Holodome Onslaught)
quince=0			; Doppelganger Pack (Jack)

[Console]
EnableConsoleCommands=1
RemoveArraySizeLimit=1
